stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

test client:
  image: node:latest
  stage: test
  script: 
    - npm install && npm run build && npm test

test server:
  image: python:latest
  stage: test
  script:
    - pip install -r api/requirements.txt && cd tests/ && python -m unittest discover .
