stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - frontend/node_modules/
  - .cache/pip
  - backend/venv

test client:
  image: node:latest
  stage: test
  script:
    - cd frontend
    - export REACT_APP_AUTH0_DOMAIN=$AUTH0_DOMAIN
    - export REACT_APP_AUTH0_CLIENT_ID=$CLIENT_ID
    - npm install
    - npm run build
    - npm test

test server:
  image: python:latest
  stage: test
  before_script:
    - cd backend
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - cd tests/
    - python -m unittest discover .
