image: node:latest
image: python:latest

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

test client:
  stage: test
  script: 
    - npm install && npm run build && npm test

test server:
  stage: test
  script:
    - pip install -r requirements.txt && cd tests/ && python -m unittest discover .
